name: Build OpenWrt

on:
  # schedule:
  #   - cron: '0 16 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 在释放磁盘空间之前
      run: |
        echo "在释放磁盘空间之前"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: 优化磁盘空间
      uses: hugoalh/disk-space-optimizer-ghaction@v0.8.1
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: "^GCC$|^G\\+\\+$|Clang|LLVM"
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: 磁盘空间释放完成
      run: |
        echo "磁盘空间释放完成"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: 拉取当前仓库
      uses: actions/checkout@v7

    - name: 添加并更新软件包
      run: |
          sed -i '1i src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main' feeds.conf.default
          sed -i '2i src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main' feeds.conf.default
          ./scripts/feeds update -a

    - name: 将“终端”插件的位置从“服务”菜单移动到“系统”菜单
      run: |
          sed -i 's|admin/services|admin/system|g' feeds/luci/applications/luci-app-ttyd/root/usr/share/luci/menu.d/luci-app-ttyd.json

    - name: 下载软件包
      run: |
          ./scripts/feeds install -a

    - name: 更新默认配置文件
      run: |
          cp diffconfig .config
          rm -rf diffconfig
          make defconfig

    - name: 跳过shadowsocksr-libev的哈希值验证
      run: |
          sed -i 's/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/' feeds/passwall_packages/shadowsocksr-libev/Makefile

    - name: 下载DL库
      run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      run: |
          make -j$(nproc) || { make -j1 V=s; }

    - name: 上传固件
      uses: actions/upload-artifact@v7
      with:
          name: OpenWrt_firmware
          path: ./bin/
